force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon_Roster__c/Pokemon_Roster__c.object-meta.xml
<CustomObject>
    <label>Pokemon Roster</label>
    <nameField>
        <label>Pokemon Roster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemon Rosters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon_Roster__c/fields/Pokemon__c.field-meta.xml
<CustomField>
    <fullName>Pokemon__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pokemon</label>
    <referenceTo>Pokemon__c</referenceTo>
    <relationshipLabel>Pokemon Rosters</relationshipLabel>
    <relationshipName>Pokemon_Rosters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pokemon_Roster__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pokemon_Rosters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ViewEntireTeamRosterApex.cls
public class ViewEntireTeamRosterApex {

    @AuraEnabled
    public static List<Pokemon_roster__c> GetFullRoster(){
        return [SELECT Name, User__c, Pokemon__r.Name from Pokemon_roster__c];
    
    }
    @auraEnabled
    public static List<Pokemon_Roster__c> getRosterSlot(){    
    		List<Pokemon_Roster__c> RosterSlotList = [SELECT Name From Pokemon_Roster__c LIMIT 10];   
        	return RosterSlotList;
}
    @AuraEnabled
	public static void deleteRosterSlots(List<Pokemon_Roster__c> lstId){
        List<Pokemon_Roster__c> ListToDelete = [SELECT Id From Pokemon_Roster__c Where Id IN:lstId];
        delete ListToDelete;
}

}